- name: Get uname
  command: uname -r
  register: os_uname

# would rather have used ansible apt-key...
- name: Add specific key
  command: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys {{docker_repo_key}}

- name: Add docker repo
  command: sudo sh -c "echo deb {{docker_repo}} docker main > /etc/apt/sources.list.d/docker.list"

- name: Install os packages
  apt: pkg={{item}} state=present update_cache=yes
  with_items: 
    - linux-image-extra-{{os_uname.stdout}}
    - lxc-docker

# consider seperate role here
- name: Change ufw forward policy to ACCEPT
  command: sed -i 's/DEFAULT_FORWARD_POLICY="DROP"/DEFAULT_FORWARD_POLICY="ACCEPT"/g' /etc/default/ufw

- name: Reload ufw
  command: ufw reload

- name: Allow incomming tcp traffic on 4243
  command: ufw allow 4243/tcp
