- name: "Import Docker APT public key."
  apt_key:
    keyserver: "{{ docker_pubkey_server }}"
    id: "{{ docker_pubkey_id }}"
    state: present
  tags:
    - docker
    - package

- name: "Install apt-transport-https if necessary."
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
  tags:
    - docker
    - package

- name: "Add the APT Docker repository."
  apt_repository:
    repo: "{{ docker_apt_repo }}"
    state: present
    filename: 'docker'
  tags:
    - docker
    - package

- name: "Install Docker"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-engine
    - linux-image-extra-virtual
  tags:
    - docker
    - package