- name: "Check CentOS version"
  fail: msg="The system is running a version of RedHat that is not supported by this playbook"
  when: ansible_distribution_major_version|int == 6
  tags:
    - docker

- name: "Make sure to remove older versions of docker"
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-engine

- name: "Install docker"
  yum:
    name: docker-ce
    enablerepo: docker-ce-stable
    state: present
  notify: Restart docker
  tags:
    - docker
    - package
