- fail: msg="The system is running a version of RedHat that is not supported by this playbook"
  when: ansible_distribution_major_version|int == 6

- name: "Install docker"
  yum: >
    name=docker-engine
    enablerepo=dockerrepo
    state=present
  notify: Restart docker

