- name: "Update the kernel"
  yum: >
    name=kernel
    state=latest
  register: kernel

- name: "Restart machine"
  shell: |
    shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true
  when: kernel|changed

- name: "Waiting for server to come back"
  local_action: >
    wait_for host={{ inventory_hostname }}
    state=started
  sudo: false
  when: kernel|changed

- name: "Update the docker dependencies"
  yum: >
    name={{ item }}
    state=latest
  with_items:
    - device-mapper

- name: "Install docker"
  yum: >
    name=docker-io
    enablerepo=epel
    state=latest
  notify: Restart Docker

- name: "Change docker options"
  lineinfile: >
    line='other_args={{ docker_opts }} {{docker_insecure_registry}}'
    regexp='^other_args='
    dest=/etc/sysconfig/docker
    state=present
  when: docker_opts != '' and docker_insecure_registry != ''
